name: Weat UI CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - name: Install dependencies
      run: yarn --frozen-lockfile
    - name: Run unit tests
      run: yarn run ci:unit
    - name: Run end-to-end tests
      run: yarn run ci:e2e
